#include "database/photo_orientation_resource.hpp"

namespace hs
{
namespace recon
{
namespace db
{

Field PhotoOrientationResource::fields_[number_of_fields_] =
{
  {"ID", FIELD_VALUE_INTEGER, FIELD_CONSTRAINT_KEY},
  {"FEATURE_MATCH_ID", FIELD_VALUE_INTEGER, FIELD_CONSTRAINT_NONE},
  {"NAME", FIELD_VALUE_TEXT, FIELD_CONSTRAINT_NONE},
  {"PATH", FIELD_VALUE_TEXT, FIELD_CONSTRAINT_NONE},
  {"FLAG", FIELD_VALUE_INTEGER, FIELD_CONSTRAINT_NONE},
  {"SCALE", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"ROTATION_X", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"ROTATION_Y", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"ROTATION_Z", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"TRANSLATE_X", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"TRANSLATE_Y", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"TRANSLATE_Z", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE}
};
const char* PhotoOrientationResource::resource_name_ = "PHOTO_ORIENTATION";
DEFINE_RESOURCE_COMMON_MEMBERS(PhotoOrientationResource)

}
}
}
