#include "database/photogroup_resource.hpp"

namespace hs
{
namespace recon
{
namespace db
{

Field PhotogroupResource::fields_[number_of_fields_]=
{
  {"ID", FIELD_VALUE_INTEGER, FIELD_CONSTRAINT_KEY},
  {"NAME", FIELD_VALUE_TEXT, FIELD_CONSTRAINT_NONE},
  {"DESCRIPTION", FIELD_VALUE_TEXT, FIELD_CONSTRAINT_NONE},
  {"WIDTH", FIELD_VALUE_INTEGER, FIELD_CONSTRAINT_NONE},
  {"HEIGHT", FIELD_VALUE_INTEGER, FIELD_CONSTRAINT_NONE},
  {"PIXEL_X_SIZE", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"PIXEL_Y_SIZE", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"FOCAL_LENGTH", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"PRINCIPAL_X", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"PRINCIPAL_Y", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"SKEW", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"RADIAL1", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"RADIAL2", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"RADIAL3", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"DECENTERING1", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE},
  {"DECENTERING2", FIELD_VALUE_REAL, FIELD_CONSTRAINT_NONE}
};

const char* PhotogroupResource::resource_name_ = "PHOTOGROUP";

DEFINE_RESOURCE_COMMON_MEMBERS(PhotogroupResource)

}
}
}
